---
- name: "Install ntp"
  apt: >
    name=ntp
    state=installed
- name: "Configure ntp"
  file: >
    src=ntp.conf
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
  notify: "Restart ntp"
- name: "Service"
  service: >
    name=ntp
    state=started
    enabled=true
