---
- name: "Install ansible ssh key"
  template: >
    src=authorized_keys.j2
    dest=/root/.ssh/authorized_keys
    owner=root
    group=root
    mode=0644
- name: "Install aptitude"
  apt: >
    name=aptitude
    state=installed
    update_cache=true
- name: "Upgrade the system"
  apt: upgrade=yes
