---
- name: "Setup sources.list.d/docker.list"
  copy: >
    src=docker.list
    dest=/etc/apt/sources.list.d/docker.list
    owner=root
    group=root
    mode=0644
- name: "Install docker PGP key"
  apt_key: >
    keyserver=pool.sks-keyservers.net
    id=58118E89F3A912897C070ADBF76221572C52609D
    state=present
- name: "Update apt"
  apt: update_cache=yes
- name: "Install docker"
  apt: >
    name=docker-engine
    state=installed
- name: "Service"
  service: >
    name=docker
    state=started
    enabled=yes
